#include <stdio.h>
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include <luajit.h>
#include <string.h>

/* Generated by build process  */
#include "index.h"

int main(int argc, char *argv[])
{
  int status;
  lua_State *L;
  
  char *test_script = "tables = {}\n\
		       tables[1] = {}\n\
		       tables[1].name = 'Programming'\n\
		       tables[1].desc = 'Programming discussion of any kind'\n\
		       tables[1].latest = 'Java is better than JavaScript?'";

  L = luaL_newstate(); 
  if (!L) {
    return -1; 
  }
  luaL_openlibs(L);

  luaL_loadbuffer(L, test_script, strlen(test_script), "");
  lua_pcall(L, 0, 0, 0);

  write(stdout, L);

  lua_close(L); // Close Lua
  return 0;
}
