#include <stdio.h>
extern "C" {
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include <luajit.h>
}
#include <string.h>
#include <pqxx/pqxx>

#include "preamble.h"
/* Generated by build process  */
#include "index.h"

int main(int argc, char *argv[])
{
    pqxx::connection c;
    pqxx::work w(c);

    int status;
    lua_State *L;
  
    L = luaL_newstate(); 
    if (!L) {
      return -1; 
    }
    luaL_openlibs(L);

    write_preamble(stdout);
    pqxx::result result = w.exec("SELECT title, description from boards");
    lua_createtable(L, result.size(), 0);
    //lua_setglobal(L, "boards");

    for(int i = 0; i < result.size(); i++) {
        lua_pushnumber(L, i + 1);
	lua_createtable(L, 0, 3);

	lua_pushstring(L, result[i][0].c_str());
	lua_setfield(L, -2, "name");
	lua_pushstring(L, result[i][1].c_str());
	lua_setfield(L, -2, "desc");

	lua_pushstring(L, "LATEST THREAD");
	lua_setfield(L, -2, "latest");

	lua_settable(L, -3);
    }

    lua_setglobal(L, "boards");
    w.commit();
    write(stdout, L);

    lua_close(L); // Close Lua
    return 0;
}
